lesson-16
cluberbogdan/py-homeworks pull request #13
Opened 2023-09-19 08:08 UTC by cluberbogdan

2023-09-19 08:10 UTC, cluberbogdan commented
![Screenshot 2023-09-19 at 11 08 42](https://github.com/cluberbogdan/py-homeworks/assets/142924009/aec24488-f1dd-412c-a741-83554018ba21)
![Screenshot 2023-09-19 at 11 09 13](https://github.com/cluberbogdan/py-homeworks/assets/142924009/2a671ffd-b917-4fd4-a6f7-5cc7bf1a13a9)

2023-09-19 14:57 UTC, bielanm requested changes
Ще або я не бачу запита на обрахунок найбільшої кількості резервацій, або ти забув його закомітити.

2023-09-19 14:57 UTC, bielanm commented on Lesson-16/SELECT-3.sql
> +);
Давай ось це також вирішимо джоінами без вкладених селектів.

2023-09-19 19:39 UTC, cluberbogdan commented on Lesson-16/SELECT-3.sql
> +);
![Screenshot 2023-09-19 at 22 39 12](https://github.com/cluberbogdan/py-homeworks/assets/142924009/676681b4-5aaa-4e02-8a45-43b282e0b760)

2023-09-19 19:40 UTC, cluberbogdan commented
![Screenshot 2023-09-19 at 22 40 11](https://github.com/cluberbogdan/py-homeworks/assets/142924009/1720a53b-b2ac-4b08-a790-9e74828408ac)

2023-09-20 21:56 UTC, bielanm commented on Lesson-16/SELECT-3.sql
> +);
останній WHERE також можна через JOIN, якщо що

2023-09-20 21:56 UTC, bielanm approved these changes

2023-09-24 16:40 UTC, merged