lesson 18
cluberbogdan/py-homeworks pull request #15
Opened 2023-09-26 19:57 UTC by cluberbogdan

2023-09-26 21:05 UTC, bielanm requested changes

2023-09-26 21:05 UTC, bielanm commented on Lesson-18/test2.py
> +        captured_output = StringIO()
давай трохи повправляємося в контекстних менеджерах, щоб подібного роду код можна було замінити на:
```
with mock_stdout() as stream:
           self.bank.update()
           self.assertIn("Overdraft letter sent for account number CA456", stream.getvalue())
```
але суть змінитися не повинна.

2023-09-27 18:40 UTC, cluberbogdan commented on Lesson-18/test2.py
> +        captured_output = StringIO()
додав новий файл test2-new.py

2023-09-28 12:03 UTC, bielanm approved these changes

2023-10-01 11:00 UTC, merged