Lesson 9
cluberbogdan/py-homeworks pull request #2
Opened 2023-08-24 11:25 UTC by cluberbogdan

Додав каталог task1 з файлами до 1 завдання 9 лекції, а також окремо файли 2 завдання 9 лекції

2023-08-24 14:48 UTC, bielanm requested changes
Привіт!

1. Оформи це будь ласка в папку з номер домашки і видали картинку, її краще додавати в сам пулл реквест там де коменти (це на майбутнє).

Загалом гуд!

2023-08-26 13:58 UTC, cluberbogdan commented
Привіт
Створив окрему папку з файлами до 2 завдання 9 лекції

2023-08-28 13:51 UTC, cluberbogdan commented
Привіт, можеш перевірити 9 лекцію, я все поправив

2023-08-28 14:00 UTC, bielanm commented
Тобі треба додати папку з віртуаленвом до .gitignore, видалити її з репозиторію, і задушити зміни. Інформація про твоє оточення в репозиторії не потрібна.

2023-08-28 14:10 UTC, cluberbogdan commented
зробив

2023-08-28 14:23 UTC, bielanm approved these changes

2023-08-28 14:54 UTC, merged