lesson 11
cluberbogdan/py-homeworks pull request #8
Opened 2023-08-31 12:04 UTC by cluberbogdan

завантажи 1 завдання 11 лекції
![Screenshot 2023-08-30 at 18 38 31](https://github.com/cluberbogdan/py-homeworks/assets/142924009/5ab95881-1f75-4696-8c99-bad8dc788e02)

2023-08-31 20:53 UTC, bielanm requested changes

2023-08-31 20:53 UTC, bielanm commented on Lesson-11/task1.py
> +    api_key = 'gOoqPUNQINVpuioUVdzWyCesJWPeV4fk'
Апі ключі в репозиторій неможна додавати: їх треба читати з файла або задавати змінною оточення. Бо якщо цей ані ключ загалом біди напевно що і не зробить, то багато сервісів знімають за запити кошти - і тому є написані кроулєри, які вишукують у репозиторіях ключі, які хтось закомітив.

2023-09-01 07:29 UTC, cluberbogdan commented on Lesson-11/task1.py
> +    api_key = 'gOoqPUNQINVpuioUVdzWyCesJWPeV4fk'
переробив на читання з вайлу ключа апі
![Screenshot 2023-09-01 at 10 23 34](https://github.com/cluberbogdan/py-homeworks/assets/142924009/a08110f5-0f7e-470c-96f0-bf31ecc9c8f7)

2023-09-02 21:14 UTC, bielanm approved these changes

2023-09-04 13:52 UTC, merged